name: CI

on: [push, pull_request]

jobs:
  microvmi:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: install latest libmicrovmi package
        run: |
        curl -s https://api.github.com/repos/Wenzel/libmicrovmi/releases/latest grep "microvmi_*.deb" \
          | cut -d '"' -f 4 \
          | wget -qi - -O microvmi.deb
        dpkg -i microvmi.deb
        rm microvmi.deb

      - name: compile microvmi LeechCore device plugin
        run: make -C leechcore_device_microvmi 
